# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, modulesPath, pkgs, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "tank/local/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "tank/local/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "tank/safe/home";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    { device = "tank/safe/persist";
      fsType = "zfs";
      neededForBoot = true;
    };

  fileSystems."/var/log" =
    { device = "tank/local/var-log";
      fsType = "zfs";
    };

  fileSystems."/replicated/db" =
    { device = "tank/replicated/db";
      fsType = "zfs";
    };

  fileSystems."/replicated/web" =
    { device = "tank/replicated/web";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0AA7-88C1";
      fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2091630e-60ef-4f13-80d1-7be6e1254d1a"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
