# .sops.yaml
keys:
  - &yubikey_authentication 614DB6CDA8EAD9CC822754057600B0BE0222D52B
  - &logic_host age1yfyla0uzflzeg6s4sh6k5lsvqqh2vl4zpegfdum4400mjtvwrexqy7eweu
  - &workstation_host age16ym4qgat67fjsmg2jh2lew56sdkg2czqnw83xk0navu7yzg56f8smm6nzv

creation_rules:
  - path_regex: secrets/.*\.yaml$
    pgp: "EF41DBC95FA2D5AC1BECBA01BFBB1FAD6D53652A"
    key_groups:
      - pgp:
          - *yubikey_authentication
        age:
          - *logic_host
          - *workstation_host
