# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e2595254-c511-461f-bfce-93bb806ec625";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "ssd" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e2595254-c511-461f-bfce-93bb806ec625";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "ssd" "noatime" ];
    };

  fileSystems."/media/storage" =
    { device = "/dev/disk/by-uuid/4903da57-a033-4d52-825d-d825a6669b84";
      fsType = "ext4";
      options = [ "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4A25-2961";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1c42422f-2a04-4e24-ae6d-d163d93dd772"; }
    ];

  networking = {
    defaultGateway = "192.168.0.1";
    hostName = "nixsrv";
    interfaces.enp9s0 = {
      ipv4.addresses = [
        {
          address = "192.168.0.44";
          prefixLength = 24;
        }
      ];
      ipv6.addresses = [
        {
          address = "fe80::5054:ff:fe28:611c";
          prefixLength = 64;
        }
      ];
      useDHCP = false;
    };
    resolvconf.enable = false;
    useDHCP = false;
    # wireless.enable = true;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.graphics.enable = true;
}
