# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "uhci_hcd"
    "ehci_pci"
    "ahci"
    "xhci_pci"
    "virtio_pci"
    "virtio_scsi"
    "usbhid"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "holt/local/root";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "holt/local/nix";
    fsType = "zfs";
  };

  fileSystems."/var/log" = {
    device = "holt/local/var-log";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "holt/safe/home";
    fsType = "zfs";
  };

  fileSystems."/persist" = {
    device = "holt/safe/persist";
    fsType = "zfs";
    neededForBoot = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2BFA-FCC9";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/d92b0120-b113-4eb3-9a56-6d92794040a9"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
